### ISSUE TITLE
different coordinate system between `tRF ID` and `Standardize tRF ID`

### ISSUE THREAD

**Issue by djunsheep** [ZWang-Lab/tRFtarget#18]
There're many tRFs having a different "starting base" between `tRF ID` and `Standardize tRF ID`

e.g:
[AspGTC-002-N-i-17-36](https://grigoriev-lab.camden.rutgers.edu/tatdb/trf_isoform.php?guide_seq=GGTGAGTATCCCCGCCTGTC)
database: tatDB
seq: GGTGAGTATCCCCGCCTGTC
start: 17
length: 20 (simply end-start+1)
Standardize tRF ID: tDR-18:36-Asp-GTC-2-M2

why is there 18???
is it a fault? or what's the point of changing the "17" to "18"? with the loss of original length info?

**Comment by az7jh2** [comment]
Hi, @djunsheep 

Thank you for the insightful question. Actually, I have not paid much attention to this before.

The conflicting annotations of the start and end indices of tRFs in the tRNA sequence between "tRF ID" and "Standardized tRF ID" arise from differences in the **coordinate systems** used by different databases. The "tRF ID" originates from the database where it is indexed, while the "Standardized tRF ID" is derived from [tDRnamer](https://trna.ucsc.edu/tDRnamer/).

Taking the tRF sequence you mentioned (GGTGAGTATCCCCGCCTGTC) as example. I searched for it in tDRnamer. The results indicate that this tRF can be derived from two tRNA sequences: [tRNA-Asp-GTC-2](http://gtrnadb.ucsc.edu/genomes/eukaryota/Hsapi38/genes/tRNA-Asp-GTC-2-1.html) and 
[tRNA-Asp-GTC-5](http://gtrnadb.ucsc.edu/genomes/eukaryota/Hsapi38/genes/tRNA-Asp-GTC-5-1.html). The alignment of the tRF on the tRNA is shown below:

![1734508338233](https://github.com/user-attachments/assets/e3b31b99-89cb-4482-a0ff-8a22d8fba3eb)

If the start index of the tRNA sequence is set to 1, the start and end indices of this tRF are 17 and 36, which is consistent precisely with the coordinate system used in tatDB.

However, the "Standardized tRF ID" derived from tDRnamer utilizes the **Sprinzl position**, a standardized coordinate system for the consensus universal secondary structure of tRNAs as well as conserved, as proposed by Sprinzl et al. in 1988 (see the publication [https://doi.org/10.1093/nar/21.13.3011](https://doi.org/10.1093/nar/21.13.3011)). Below are the Sprinzl coordinates of a tRNA sequence. Circles represent nudeotides which are always present; and the ovals represent nudeotides which are not present in every structure. Note that **the start index begins at 0**, and **some positions share the same numerical label**, such as 17 and 17a, as well as 20, 20a, and 20b. 

![1734509015128(1)](https://github.com/user-attachments/assets/c47086e9-d76e-4952-b11a-9bb68f6ea2d6)

Below is the alignment of the tRF to the tRNA secondary structure generated by tDRnamer. According to the Sprinzl coordinates, positions 17, 17a, and 20b are absent, resulting in start and end indices of 18 and 36, as indicated in the "Standardized tRF ID".

![modified](https://github.com/user-attachments/assets/0272dc7c-fc8f-4ee1-aa43-33ffd6580eeb)

Your question reminds me that it might be a good idea to highlight the unique coordinate system used in the "Standardized tRF ID" to avoid confusion. We will consider this in future updates.

**Comment by djunsheep** [comment]
Thanks @az7jh2. And yes it's a good idea to highlight different coordinate systems.
So the Sprinzl coordinates are actually "rank label" of the base positions and may not be exactly the continuous numeric coordinates. It's good for alignment but not applicable in absolute coordinates and length identification (that I was scripting on).
